title: "Maria (Masha) Cheremisinova"
tab_title: Maria Cheremisinova
description: "Personal academic page"
theme: minima
header_pages:
  - index.md
  - pages/publications.md
  - pages/teaching.md
  - pages/fieldwork.md

author:
  name: "Maria (Masha) Cheremisinova"
  email: "mcheremisinova@utexas.edu"
  affiliation: "PhD candidate, The University of Texas at Austin"
  scholar: "https://scholar.google.ru/citations?user=RoF1l1UAAAAJ&hl=en&authuser=1"
  cv: "/assets/CV_Cheremisinova_2026apr.pdf"
  photo: /assets/img/profile.jpeg

plugins:
  - jekyll-sitemap
